import { formatLastSaved, formatTime } from '@/utils/date-formatters';

export const useHeaderReturn = (props) => {
  const {
    isAuthenticated,
    displayFlowName,
    nodeCount,
    edgeCount,
    optionsMenuOpen,
    setOptionsMenuOpen,
    optionsMenuRef,
    isSaving,
    saveStatus,
    notification,
    time,
    handleSaveFlow,
    actions,
    modalActions,
    lastSaved,
    openTemplatesModal,
    storeTemplatesModal,
    openSimulateModal,
    storeSimulateModal,
    openShareModal,
    storeShareModal,
    openModal,
    showNotification,
    nodes,
    edges,
    plubotId,
  } = props;

  return {
    isAuthenticated,
    displayFlowName,
    nodeCount,
    edgeCount,
    optionsMenuOpen,
    setOptionsMenuOpen,
    optionsMenuRef,
    isSaving,
    saveStatus,
    notification,
    time,
    handleSaveFlow,
    ...actions,
    ...modalActions,
    formatLastSaved: () => formatLastSaved(lastSaved),
    formatTime: () => formatTime(time),
    finalTemplatesModal: openTemplatesModal ?? storeTemplatesModal,
    finalSimulateModal: openSimulateModal ?? storeSimulateModal,
    finalShareModal: openShareModal ?? storeShareModal,
    openModal,
    showNotification,
    nodes,
    edges,
    lastSaved,
    plubotId,
  };
};
