import { formatLastSaved, formatTime } from '@/utils/date-formatters';

export const useHeaderReturn = (props) => {
  const {
    isAuthenticated,
    displayFlowName,
    nodeCount,
    edgeCount,
    optionsMenuOpen,
    setOptionsMenuOpen,
    optionsMenuRef,
    isSaving,
    saveStatus,
    notification,
    time,
    handleSaveFlow,
    actions,
    modalActions,
    lastSaved,
    openTemplatesModal,
    storeTemplatesModal,
    openSimulateModal,
    storeSimulateModal,
    openShareModal,
    storeShareModal,
    openModal,
    showNotification,
    nodes,
    edges,
    plubotId,
    handleOpenVersionHistory,
    handleOpenImportExport,
    handleOpenSettingsModal,
    handleOpenPathAnalysis,
  } = props;

  // Los handlers vienen en modalActions, no directamente en props
  const handlers = {
    handleOpenVersionHistory: modalActions?.handleOpenVersionHistory || handleOpenVersionHistory,
    handleOpenImportExport: modalActions?.handleOpenImportExport || handleOpenImportExport,
    handleOpenSettingsModal: modalActions?.handleOpenSettingsModal || handleOpenSettingsModal,
    handleOpenPathAnalysis: modalActions?.handleOpenPathAnalysis || handleOpenPathAnalysis,
  };

  return {
    isAuthenticated,
    displayFlowName,
    nodeCount,
    edgeCount,
    optionsMenuOpen,
    setOptionsMenuOpen,
    optionsMenuRef,
    isSaving,
    saveStatus,
    notification,
    time,
    handleSaveFlow,
    ...actions,
    ...handlers,
    formatLastSaved: () => formatLastSaved(lastSaved),
    formatTime: () => formatTime(time),
    finalTemplatesModal: openTemplatesModal ?? storeTemplatesModal,
    finalSimulateModal: openSimulateModal ?? storeSimulateModal,
    finalShareModal: openShareModal ?? storeShareModal,
    openModal,
    showNotification,
    nodes,
    edges,
    lastSaved,
    plubotId,
  };
};
