import { useMemo } from 'react';

// eslint-disable-next-line max-lines-per-function
export const useNodeReturn = (props) => {
  const {
    isResizing,
    isCollapsed,
    isEditing,
    setIsEditing,
    showContextMenu,
    contextMenuPosition,
    errorMessage,
    isHovered,
    nodeReference,
    toggleCollapse,
    handleContextMenu,
    handleClick,
    handleMouseDown,
    handleDoubleClick,
    updateNodeData,
    setShowContextMenu,
    setIsHovered,
    showError,
    getStatusClass,
    canEdit,
    canDelete,
    isConnectable,
    minWidth,
    minHeight,
    initialWidth,
    initialHeight,
  } = props;

  return useMemo(
    () => ({
      isResizing,
      isCollapsed,
      isEditing,
      setIsEditing,
      showContextMenu,
      contextMenuPosition,
      errorMessage,
      isHovered,
      nodeRef: nodeReference,
      toggleCollapse,
      handleContextMenu,
      handleClick,
      handleMouseDown,
      handleDoubleClick,
      updateNodeData,
      setShowContextMenu,
      setIsHovered,
      showError,
      getStatusClass,
      canEdit,
      canDelete,
      isConnectable,
      minWidth,
      minHeight,
      initialWidth,
      initialHeight,
    }),
    [
      isResizing,
      isCollapsed,
      isEditing,
      setIsEditing,
      showContextMenu,
      contextMenuPosition,
      errorMessage,
      isHovered,
      nodeReference,
      toggleCollapse,
      handleContextMenu,
      handleClick,
      handleMouseDown,
      handleDoubleClick,
      updateNodeData,
      setShowContextMenu,
      setIsHovered,
      showError,
      getStatusClass,
      canEdit,
      canDelete,
      isConnectable,
      minWidth,
      minHeight,
      initialWidth,
      initialHeight,
    ],
  );
};
