"""Add embed fields to Plubot model

Revision ID: 08175f882318
Revises: c9cd14361cde
Create Date: 2025-05-09 23:20:44.391036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08175f882318'
down_revision = 'c9cd14361cde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
