"""Add embed fields to Plubot model

Revision ID: c9cd14361cde
Revises: fb80ecf5ec8e
Create Date: 2025-05-09 23:20:14.624103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9cd14361cde'
down_revision = 'fb80ecf5ec8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plubots', sa.Column('public_id', sa.String(), nullable=True))
    op.add_column('plubots', sa.Column('embed_config', sa.JSON(), nullable=True))
    op.add_column('plubots', sa.Column('is_embeddable', sa.Boolean(), nullable=True))
    op.add_column('plubots', sa.Column('embed_domains', sa.JSON(), nullable=True))
    op.add_column('plubots', sa.Column('qr_code_url', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'plubots', ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plubots', type_='unique')
    op.drop_column('plubots', 'qr_code_url')
    op.drop_column('plubots', 'embed_domains')
    op.drop_column('plubots', 'is_embeddable')
    op.drop_column('plubots', 'embed_config')
    op.drop_column('plubots', 'public_id')
    # ### end Alembic commands ###
