"""Add color and powers to chatbots table

Revision ID: d924d76d7f78
Revises: 9f0ced2eab9a
Create Date: 2025-04-23 20:49:51.466234

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd924d76d7f78'
down_revision = '9f0ced2eab9a'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('powers', sa.String(), nullable=True))

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbots', schema=None) as batch_op:
        batch_op.drop_column('powers')
        batch_op.drop_column('color')

    # ### end Alembic commands ###